### ISSUE TITLE
Update api to v1alpha2

### ISSUE THREAD

**Issue by zoumo** [caicloud/loadbalancer-controller#31]
### According to Kubernetes‘s change :
- update TPR to CRD

### API update:
- move api to https://github.com/caicloud/clientset
- automatically generate clients and informers
- update api to v1apha2, delete useless field.
- change api group from `net.alpha.caicloud.io` to `loadbalance.caicloud.io`
- adjust the default port to let them less than 1024

### Repo convention:
- readjust directory structure

### Bug fix:
- fix https://github.com/caicloud/loadbalancer-controller/issues/25
- update nginx ingress controller to 0.9.0-beta.15, fix https://github.com/caicloud/loadbalancer-controller/issues/33
- adjust proxy read/write timeout to 10min

**Comment by zoumo** [comment]
v1alpha2 api spec
```
spec:
  nodes:
    names:
    - kube-master-1
    - kube-master-2
    - kube-master-3
    replica: 3
    taintEffect: PreferNoSchedule
  providers:
    ipvsdr:
      scheduler: rr
      vip: 192.168.18.60
  proxy:
    type: nginx
    config:
      proxy-read-timeout: "600"
      proxy-send-timeout: "600"
      use-proxy-protocol: "false"
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 300m
        memory: 256Mi
```
