### ISSUE TITLE
[BUG] controller will crash when I change provider from ipvs to external

### ISSUE THREAD

**Issue by zoumo** [caicloud/loadbalancer-controller#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
I changed a running loadbalancer from
```yaml
  spec:
    providers:
      ipvsdr:
        scheduler: rr
        vip: 192.168.19.222
```
to
```yaml
  spec:
    providers:
      external:
        vip: 192.168.19.222
```
the controller crashed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
